---
AWSTemplateFormatVersion: '2010-09-09'
Description: Auto Scaling with EC2

Parameters:
  VPCID:
    Description: VPC ID for the instances
    Type: AWS::EC2::VPC::Id

  Subnet1ID:
    Description: Subnet ID in AZ1
    Type: AWS::EC2::Subnet::Id

  Subnet2ID:
    Description: Subnet ID in AZ2
    Type: AWS::EC2::Subnet::Id

  CustomAMI:
    Description: custom Amazon Linux 2 AMI
    Type: AWS::EC2::Image::Id

  TargetGroupARN1:
    Description: ALB Target Group1
    Type: String
  
  TargetGroupARN2:
    Description: ALB Target Group2
    Type: String

Resources:
  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
        - !Ref Subnet1ID
        - !Ref Subnet2ID
      LaunchConfigurationName: !Ref LaunchConfiguration
      MinSize: '2'
      MaxSize: '4'
      DesiredCapacity: '2'
      TargetGroupARNs:
        - !Ref TargetGroupARN1
        - !Ref TargetGroupARN2

  LaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: !Ref CustomAMI
      InstanceType: t2.micro
      KeyName: teradaterraform
      SecurityGroups:
        - !Ref InstanceSecurityGroup

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access and HTTP access
      VpcId: !Ref VPCID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
